version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Passou pela fase de instalação

  pre_build:
    commands:
      - chmod 777 ./gradlew

  build:
    commands:
      - ./gradlew clean build
      - ./gradlew test

  post_build:
    commands:
      - sudo ./gradlew dockerfile
      - ./gradlew dockerBuild
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/key-manager-rest-*-all.jar