version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo Passou pela fase de instalação

  build:
    commands:
      - gradlew test
      - gradlew clean build

  post_build:
    commands:
      - gradlew dockerfile
      - gradlew dockerBuild
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/key-manager-rest-*-all.jar