micronaut:
  application:
    name: keyManagerRest

grpc:
  server:
    enabled: false
  client:
    plaintext: true
    max-retry-attemps: 10
  channels:
    key-manager:
      address: '${KEY_MANAGER_GRPC_ENDPOINT:localhost}:50051'
      plaintext: true