apiVersion: v1
kind: Service
metadata:
  name: pix-key-manager-rest-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: pix-key-manager-rest-deploy
  ports:
  - port: 80
    targetPort: 8080
